title: "Archives Lieneson et Menet"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

url: "https://menetal-source.github.io"
baseurl: "/archives-famille" # <--- Vérifie bien que c'est le nom exact de ton dépôt

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: "single"
      author_profile: true
      sidebar:
        nav: "docs"
