title: "Archives Lieneson et Menet"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"
baseurl: "/archives-famille"
url: "https://menetal-source.github.io"

# Cette section est CRUCIALE pour la barre latérale
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      sidebar:
        nav: "docs" # Nom du menu dans _data/navigation.yml
        author:
  name: "Famille L&M"
  bio: "Portail généalogique"
