---
layout: single
author_profile: true
title: ""  # On laisse le titre vide ici pour qu'il n'apparaisse pas en haut à gauche
sidebar:
  nav: "docs"
---

title: "Archives Lieneson et Menet"
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: default

url: "https://menetal-source.github.io"
baseurl: "/archives-famille"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      sidebar:
        nav: "docs"
        
# Personnalisation de la couleur de fond
minimal_mistakes_skin: "default"
header:
  overlay_color: "#e3f2fd" # Un bleu ciel très léger pour le haut

# On ajoute un style direct pour le corps de la page
remote_theme: mmistakes/minimal-mistakes@4.24.0
