title: "Archives Lieneson et Menet"
# On supprime la ligne theme: minima si elle existe encore
theme: null
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

baseurl: "/archives-famille"
url: "https://menetal-source.github.io"

include: ["_pages", "_data"]

defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      sidebar:
        nav: "docs"
