remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

url: "https://menetal-source.github.io"
baseurl: "/archives-famille"

# On vide les titres automatiques pour ne laisser que ton travail
title: ""
description: ""
logo: 

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: "single"
      author_profile: false
      # On force la suppression du titre de page automatique
      title: ""
