remote_theme: "mmistakes/minimal-mistakes@4.24.0"
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "default"

url: "https://menetal-source.github.io"
baseurl: "/archives-famille"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: "single"
      author_profile: false
